name: Update Packages

on:
  schedule:
    - cron: "8 * * * *"
    - cron: "29 * * * *"
    - cron: "53 * * * *"
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Setup cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install Komac
        run: cargo binstall komac -y
      - name: Sync Fork
        env:
          KOMAC_FORK_OWNER: UnownPlain
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: |
          komac sync
          komac cleanup -a
      - name: Update Packages
        env:
          KOMAC_FORK_OWNER: UnownPlain
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: deno run start
      # - name: Install Komac (Nightly)
      #   if: ${{ steps.continue.outputs.result }}
      #   run: |
      #     wget -P /usr/local/bin/ https://github.com/russellbanks/Komac/releases/download/nightly/komac-nightly-x86_64-unknown-linux-gnu.tar.gz
      #     tar -xf /usr/local/bin/komac-nightly-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin/
      #     echo "/usr/local/bin/" >> $GITHUB_PATH
